---
title: "寮について"
---
<div style="height: 20px;"></div>
アメリカの大学は寮制のところがかなり多い。Harvardも例外ではない。さて、寮と聞くとハリー・ポッターに出てくるように、性格の異なる寮が複数あってその間でドラマが繰り広げられる、というようなものを想像する方もいるかもしれない。流石にフィクションほどではないが、大体それで正解である。例えば、Harvardでは自己紹介のとき、氏名の後に住んでいる寮の名前を挙げることが多い。それくらいどの寮に入っているかというのは重要なのである。そこで、今回はHarvardの寮について話をしようと思う。

Harvardでは一年生は全員dormと呼ばれる寮にすむ。DormたちはYardという大きな中庭の中にあって、ここは観光名所にもなっている。Dormごとに性格の違いはあって、例えばこの寮は静かであの寮はパーティー気質だ、という風な認識が共有されている。学生は入学前に入寮アンケートなるものに回答する。そこでは、就寝や起床の時間、希望するルームメイトの人数、どれくらい賑やかな環境が好きか、あるいは静かな空間を好むか、と言ったことに詳しく答えていく。大学の担当者はその結果をもとに人々をdormsに「振り分け」ていくのである。1学年700名をできるだけそれぞれの希望に沿うように家々に入れていくのは難しいと思うのだが、割とうまく行っているようである（それでもローカルな問題, i.e., ルームメイト同士のいざこざは防ぎようがない）。

そうして一年生の春学期になると再び寮の振り分けがある。今度移る寮はhouseと呼ばれ、こちらは二年から四年までの3年間を同じ寮で過ごすことになる。学生たちは2〜8名のblocking groupを組み、同じグループのメンバーは同じ寮の比較的近い部屋に割り振られる。もちろん、一匹狼として振り分けに参加することもできる。学期の真ん中にhousing dayというのが存在して、この日の朝、同じblocking groupのメンバーはあらかじめ届け出た部屋に集まる。そこに、自分達がいくことになる寮の先輩が訪れて、結果を知るのである。

このように、Harvardのhousing systemは何かと他者との共同生活を要求することが多い。一年〜二年生の間は1人部屋というのはなかなかないし、housing dayに際してはblocking groupを組むことを要求される。生活の際にプライベートな空間が提供されることはほとんどない。この辺りがストレスの原因になったりもする。ちなみに、お隣のMITは全員1人部屋で、三年生からは寮を出て近くのアパートに住むことも可能らしい。大学の性格がよく出ているように思う。

そうはいっても、深夜まで食堂で一緒に勉強できる環境は他では得られないものである。数々のリビング・ミーティングルームに図書館や防音室、ジムなど設備は充実している。中には自前のオペラハウスを持つ寮まである。食事を除いては非常に満足度の高い生活を送れているように思う。