---
title: "ローガン国際空港"
---
<div style="height: 20px;"></div>
ボストンは海に面していて、他の港町と同じく岸から少し離れたところに空港がある。本当の名前はもっと長いのだが、ローガンといえばこの空港である。もちろん、ボストンでは誰もローガンなどとは呼ばず、the airportで通じる。

いかにも平均的なアメリカの空港といった感じで、そこまで大きくはないが、サービス等は充実している。ターミナルはAからCまでが国内線とカナダ行きに割り当てられていて、Eが国際線用になっている。これらは全て真ん中の駐車場に伸びる通路でつながっていて、なかなか効率的である。

ボストン市街から公共交通機関を使って空港に行くのには2通りの方法がある。一つ目はSouth Stationというところから出ているSilver Lineというのに乗るもので、あるいはBlue Lineというのを使ってもよい。どちらも2つの車両がつながったバスで、10〜20分ほどの荒い運転を耐えてようやく空港に到着する。ちなみに、空港から市街に向けてこれらのシャトルバスを使う際はタダとなる。

私が最初にローガンを使ったのはボストンからアメリカに入国した時であった。19時くらいに羽田を出て、確か到着が同時刻くらいだった。14時間のフライトで時差が同じく14時間あったから、納得である。飛行機を降りると目の前に巨大な星条旗が飛び込んできて、アメリカに着いたのを実感したのを覚えている。入国審査は、どこでもそうなのだが、とても事務的だった。長い列にならばされたので1時間くらいかかっただろうか。

逆に、ボストンから出発するタイミングでこの空港を初めて使ったのは、入国から3ヶ月後の12月であった。帰国があまりに楽しみで離陸が朝7時だったが、前日の夕方3時には空港に着いてしまった。この時はまだコロナの規制が厳しくて、日本に入国するためには厚生労働省が指定する検査方法で検査を受け、外務省が用意したフォーマットに医師からサインをもらわなくてはいけないのであった。他の国でもまだ規制があったのであろうか、ターミナルEの検査場には長蛇の列ができていた。あらかじめ予約した上で2時間前に空港に着いたのだが1時間経っても一向に列が進まず、やがて閉店の17時が近づいてきた。しかしまだ前には50人くらいおり、周りがひどく焦り始める。中には、空港を出て市内の病院で検査を受けようと声をかけ始める人も出てきた。その場にいた警備員のような人に至っては、列の後ろの方に向かって「お前はもう今日テストを受けられる見込みはないから諦めろ」と語りかける始末である。ここまできて日本に帰れないのはいくらなんでも悲しすぎる、ということで冷静になって列の先頭に歩いていってみたところ、なんと列は2つあって、自分が並んでいたのは予約した人のためのものではなくwalk-in専用の列であることが判明した。危機一髪。