---
title: "プロローグ"
---
<div style="height: 20px;"></div>
まことに小さな街が、成熟期を迎えようとしている。

<!--「小さな」といえば、平成末期の...と茶番はこれくらいにして、ともかくも、我々は一人の少年の跡を追わねばならない。-->
---

大阪・北摂の中心地、梅田には、JR、阪急、阪神、大阪メトロと関西の鉄道各社の「大阪駅」が集結している。そこから北へ1キロも行かないところ、淀川の南岸に、中津とよばれる地域がある。ここから府北部の妙見山まで伸びる道のりには寺社仏閣が点在し、江戸時代から重要な役割を果たしていたようだ。この経路は現在でも「能勢街道」として知られている。

大阪市街を出て能勢街道沿いに北上すると、京都は羅城門から下関まで伸びる西国街道と交差する。この場所を「石橋」とよぶ。名前の由来となった石の橋は、両街道の交差する川にかかっていたとされ、いわれ石として現地の小学校で展示されている。石橋の周辺は江戸時代から「瀬川宿」なる宿場として栄えていたようで、瀬川という名前は今日でも地名に残っている。

さて阪急電鉄石橋駅を下車して東に進むと、小高い山が見えてくる。待兼山（まちかねやま）といい、枕草子にも登場する、由緒ある山である。この山の大部分は大阪大学の豊中キャンパスで占められている。大学の土地は、名が示すように、行政上は池田市石橋ではなく隣接する豊中市に位置する。それでも、キャンパス西側の最寄り駅は石橋駅であり、電車で通学する学生の多くは市を越境して登校することになる。

この山にはもう一つの特徴がある。1964年、阪大理学部の新校舎建設現場から骨の破片が発見された。これを機に本格的な発掘調査が行われ、最終的に脊椎動物の骨格化石が、欠陥の少ない形で確認された。のちに「マチカネワニ」と名付けられることになるこの出土物は、日本初のワニ化石とされている。

マチカネワニの骨格標本は、キャンパスのさまざまな場所に展示されている。その中でも目を引くのが、総合学術博物館の受付横の標本である。石橋駅からキャンパスまでの道中、ちょうど大学の敷地内に入ったところで、坂を登る学生の波から外れ左に進むと、小さな博物館にたどりつく。建物に入るとすぐ、吹き抜けの壁にハリツケにされたマチカネワニの全身骨格の模型が現れる。今や大学のマスコットとして「ゆるキャラ化」されてしまったマチカネワニだが、こちらのワニは威厳を保っている。

私は幼少期を、この街と、そしてワニと共に過ごした。幼い私にとって、大学とは学び場というよりは、坂の上のワニの住む博物館で静かな土日を過ごすための休憩所であった。古代生物と未来への希望溢れる学部生の混ざり合うこの興味深い街の話を、もう少し続けようと思う。