---
title: "カラスが鳴く"
---
<div style="height: 20px;"></div>
物理の話を始めるとき、何の話から始めるべきだろうか？

物理を学ぶ人間はよく、物理を学んでいない人に、自分がなぜ物理を学んでいるのか説明する機会を得る。やり方は人それぞれである。私は、カラスの話から始めることにしている。
---

ワニの鎮座する待兼山には、カラスの集団の寝ぐらが存在する。明け方、カラスたちは山から街に出勤し、その後は食べものを漁ったりのんびりしたりして過ごす。彼らのお気に入りスポットの一つが、石橋駅近くの公園、「駅前公園」である。大学生で賑わう石橋駅前には飲食店が立ち並び、そのおかげでカラスたちは食事に困ることがない。駅前公園は、ゴミ捨て場を行き来する際の中継点として重要な役割を果たしている。

大都心ほど人馴れしていない石橋のカラスは、通勤通学で慌ただしく行き来する人の流れの間隙を縫って、道路に捨てられたゴミを漁る。しかしそんなふうにカラスが人間たちを注意深く観察しているとき、実はまた彼らも人間によって注意深く観察されていたのである。

私は小学生のころ、カラスの観察を日課としていた。週に3回ほど、登校前の朝7時に駅前公園に向かい、決められた時間（たしか10分だったように記憶している）カラスを観察する。観察とはすなわち、公園にいるカラスの数、どこにいるか、どう飛び回ったか、誰が何回「カァ」と鳴いたかを記録する。小学生らしく動画などは用いず、民博の『梅棹忠夫展』で知った10cm四方の型紙カードに全てを手書きで記録し、保存する手法をとった。

確か小学4年生だったと思うが、鳴き声のパターンに注目してデータを分析した年がある。あるカラスが「カァカァカァ...」と鳴く様子を想像してほしい。これらは、連続して発声されるカァごとにフレーズとして分割することができる。例えば、「カァカァ（5秒の間）カァカァ」の場合は2フレーズで、それぞれに「カァ」が2回含まれる、という要領。さて、1フレーズに含まれる「カァ」の回数について、以下のような事実が判明した。まず、最も頻度が高いのは「カァ」が$n=1$回の場合。そして$n$個のカァで構成されるフレーズについてだが、その頻度を$P(n)$とすると、小さな$n$について

$$
P(2n), P(2n+2) > P(2n+1)
$$

という“偶数回優位”の法則が発見された。すなわち、「カァカァ」は「カァカァカァ」よりも頻度が高く、さらに「カァカァカァ」よりも「カァカァカァカァ」の方が頻繁に見られる。もう少し大局的には$P(n)$は$n$とともに減少していくのだが、その中で局所的には偶数回の「カァ」は奇数回よりも好まれることが判明した。

物事をじっくり観察すると、それらを支配する法則、モノのコトワリとでもいえるものが見えてくる。カラスの鳴き声の分析は、私がそれを初めて自分で掴み取った“事件”であったように思う。

観察し、仕組みを理解する。私の物理学的活動の根幹にはその精神が根付いている。今も物理を続けているということは、そういうものが自分に合っているからなのだろうと納得している。
