#!/usr/bin/env python3
"""Assemble renju_engine.qmd from the sources in this directory.

    python3 _renju_src/build.py

Everything the page needs is inlined into a single <script> block so the page
stays a self-contained Quarto document (no extra resources to copy into docs/).
"""
import pathlib, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / 'renju_engine.qmd'

head = (HERE / 'page.html').read_text()
core = (HERE / 'core.js').read_text()
ui   = (HERE / 'ui.js').read_text()

banner = ("<!-- Generated by _renju_src/build.py - edit the sources in _renju_src/, "
          "not this file. -->\n")

doc = head + '\n' + core + '\n' + ui + '\n</script>\n```\n'
# put the "do not edit" note right after the YAML block
first, rest = doc.split('---\n', 2)[1], doc.split('---\n', 2)[2]
doc = '---\n' + first + '---\n' + banner + rest
OUT.write_text(doc)
print(f'wrote {OUT} ({len(doc)} bytes)')
